
spring:
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Password
  sql:
    init:
      schema-locations: classpath:iniSql/schema.sql
      data-locations: iniSql/data.sql
      mode: always

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate:
      type.descriptor.sql: DEBUG
      SQL: DEBUG
      type: trace
